<?php
include_once("root.php");
include_once(ROOT."classes/admin/textfield.php");
include_once(ROOT."classes/admin/select.php");
include_once(ROOT."classes/admin/idbox.php");
include_once(ROOT."classes/admin/textarea.php");
include_once(ROOT."classes/admin/tt.php");
include_once(ROOT."classes/admin/checkbox.php");
include_once(ROOT."classes/admin/yesno.php");
include_once(ROOT."classes/admin/status.php");
include_once(ROOT."classes/admin/perms.php");
include_once(ROOT."classes/admin/upload.php");
include_once(ROOT."classes/admin/password.php");
include_once(ROOT."classes/admin/xmllist.php");
include_once(ROOT."classes/admin/image.php");
include_once(ROOT."classes/admin/sizefield.php");
include_once(ROOT."classes/admin/finduser.php");
include_once(ROOT."classes/admin/findvideo.php");
include_once(ROOT."classes/admin/categories.php");
include_once(ROOT."classes/admin/orden.php");
include_once(ROOT."classes/admin/upload_image.php");
include_once(ROOT."classes/admin/multiconversion.php");
//include_once(ROOT."classes/admin/hidden_elements.php");
?>