<?php
$map=array(
	"" => "CHome",
	"categories" => "CCategories",
	"category" => "CCategory",
	"search" => "CSearch",
	"channels" => "CChannels",
	"video" => "CVideo",
	"videos" => "CVideos",
	"channel" => "CChannel",
	"myvideos" => "CMyVideos",
	"login" => "CLogin",
	"logout" => "CLogout",
	"users" => "CUsers",
	"upload" => "CUpload",
	"uploadform" => "CUploadForm",
	"uploaddetails" => "CUploadDetails",
	"uploadsuccess" => "CUploadSuccess",
	"uploadfile" => "CUploadFile",
	"subscriptions" => "CSubscriptions",
	"subscribe" => "CSubscribe",
	"unsubscribe" => "CUnsubscribe",
	"favorites" => "CFavorites",
	"favorites_remove" => "CRemoveFavorite",
	"favorites_add" => "CAddFavorite",
	"signup" => "CSignup",
	"completesignup" => "CCompleteSignup",
	"filename" => "CFilename",
	"subscription" => "CSubscription",
	"rate" => "CRate",
	"similar" => "CSimilarVideos",
	"subscription_thumbs" => "CSubscriptionThumbs",
	"report_video" => "CReportVideo",
	"report_comment" => "CReportComment",
	"playlists" => "CPlaylists",
	"playlist" => "CPlaylist",
	"remove_playlist" => "CRemovePlaylist",
	"remove_playlistvideo" => "CRemovePlaylistVideo",
	"create_playlist" => "CCreatePlaylist",
	"play_playlist" => "CPlayPlaylist",
	"comments" => "CComments",
	"page" => "CPage",
	"account" => "CAccount",
	"updateaccount" => "CUpdateAccount",
	"reset_password" => "CResetPassword",
	"completepasswordreset" => "CCompletePasswordReset",
	"edit_channel" => "CEditChannel",
	"reorderplaylist" => "CReorderPlaylist",
	"editplaylist" => "CEditPlaylist",
	"searchsimilar" => "CSearchSimilarVideos",
	"video_thumb" => "CVideoThumb",
	"logo" => "CLogo",
	"actonplaylist" => "CActOnPlaylist",
	"channelpreview" => "CChannelThumbs",
	"channelvideos" => "CChannelVideos",
	"searchpreview" => "CSearchThumbs",
	"lang" => "CSwitchLang",
	"webcam" => "CWebcam",
	"processqueue" => "CProcessQueue",
	"showimage" => "CShowImage",
	"setprivate" => "CSetPrivate",
	"ssrequests" => "CSubscriptionRequests",
	"inbox" => "CInbox",
	"messages" => "CMessages",
	"message" => "CMessage",
	"managemessage" => "CManageMessage",
	"ssrequestaccept" => "CSSRequestAccept",
	"ssrequestreject" => "CSSRequestReject",
	"subscribers" => "CSubscribers",
	"remove_subscribers" => "CRemoveSubscribers",
	"newmessage" => "CNewMessage",
	"sendmessage" => "CSendMessage",
	"replymessage" => "CReplyMessage",
	"savechannel" => "CSaveChannel",
	"edit_profile" => "CEditProfile",
	"saveprofile" => "CSaveProfile",
	"mychannel" => "CMyChannel",
	"edit_layout" => "CEditLayout",
	"savelayout" => "CSaveLayout",
	"emoticons" => "CEmoticons",
	"edit_vlog" => "CEditVLog",
	"removevlog" => "CRemoveVLog",
	"addtovlog" => "CAddToVLog",
	"vlog" => "CVLog",
	"edit_video" => "CEditVideo",
	"save_video" => "CSaveVideo",
	"vlogrss" => "CVLogRSS",
	"latestrss" => "CLatestRSS",
	"categoryrss" => "CCategoryRSS",
	"friends" => "CFriends",
	"invite" => "CInvite",
	"send_invitation" => "CSendInvitation",
	"accept_invitation" => "CAcceptInvitation",
	"remove_friends" => "CRemoveFriends",
	"randomvideo" => "CRandomVideo",
	"groups" => "CGroups",
	"group" => "CGroup",
	"newgroup" => "CNewGroup",
	"creategroup" => "CCreateGroup",
	"allgroups" => "CAllGroups",
	"ownedgroups" => "COwnedGroups",
	"editgroup" => "CEditGroup",
	"savegroup" => "CSaveGroup",
	"addtogroup" => "CAddToGroup",
	"joingroup" => "CJoinGroup",
	"discussions" => "CDiscussions",
	"discussion" => "CDiscussion",
	"newdiscussion" => "CNewDiscussion",
	"creatediscussion" => "CCreateDiscussion",
	"editdiscussion" => "CEditDiscussion",
	"savediscussion" => "CSaveDiscussion",
	"postdiscussion" => "CPostDiscussion",
	"removefromgroup" => "CRemoveFromGroup",
	"deletediscussion" => "CDeleteDiscussion",
	"deletepost" => "CDeletePost",
	"groupmembers" => "CGroupMembers",
	"removememberfromgroup" => "CRemoveGroupMember",
	"download" => "CDownload",
	"latest" => "CTopLatest",
	"embedvideo" => "CEmbedVideo",
	"tellafriend" => "CTellAFriend",
	"tafsend" => "CTAFSend",
	"enable_video" => "CEnableVideo",
	"edit_category" => "CEditCategory",
	"save_category" => "CSaveCategory",
	"enable_channel" => "CEnableChannel",
	"enable_group" => "CEnableGroup",
	"enable_comment" => "CEnableComment",
	"watched" => "CWatchedVideos",
	"upgrade" => "CUpgrade",
	"buy" => "CBuy",
	"processpayment" => "CProcessPayment",
	"addtags" => "CAddTags",
	"tagvideo" => "CTagVideo",
	"watchhere" => "CWatchHere",
	"videoads" => "CVideoAds",
	"usercp" => "CUserCP",
	"pending" => "CPending",
	"stats" => "CStats",
	"videothumbs" => "CVideoThumbs",
	"createalbum" => "CCreateAlbum",
	"savealbum" => "CSaveAlbum",
	"picture" => "CPicture",
	"removepicture" => "CRemovePicture",
	"addtoalbum" => "CAddToAlbum",
	"createreport" => "CCreateReport",
	"savereport" => "CSaveReport",
	"reports" => "CReports",
	"viewreport" => "CReport",
	"resolvereport" => "CResolveReport",
	"activateaccount" => "CActivateAccount",
	"validate" => "CValidate",
);

$noncached=array(
	"users",
	"signup",
	"download",
	"rate",
	"report_video",
	"report_comment",
	"logout",
	"login",
	"edit_video",
	"subscribe",
	"unsubscribe",
	"favorites_remove",
	"favorites_add",
	"remove_playlist",
	"remove_playlistvideo",
	"create_playlist",
	"updateaccount",
	"reset_password",
	"setprivate",
	"upload",
	"uploadform",
	"uploaddetails",
	"uploadfile",
	"newmessage",
	"replymessage",
	"randomvideo",
	"processqueue",
	"video",
	"watched"
);
?>